### ISSUE TITLE
[Feature Request] Add support for SAML SSO

### ISSUE THREAD

**Issue by yarons** [cogolabs/beyond#1]
Thank you so much for this project, adding SAML SSO will make it even better for all sort of uses.

**Comment by presbrey** [comment]
@yarons Thanks for the kind words regarding the project! Agreed, Interested to hear more about uses and scalability.

Got SAML working well with a few Cloud and Open Source SAML IdPs. Hope I provided enough options for interoperability with everyone's configurations. PRs welcome as always!

SAML release here: https://github.com/cogolabs/beyond/releases/tag/v1.8.5

`docker pull ghcr.io/cogolabs/beyond:v1.8.5`

**Comment by yarons** [comment]
Thank you :)
